### ISSUE TITLE
pop_tools trying to download files already local to cheyenne

### ISSUE THREAD

**Issue by emaroon** [NCAR/pop-tools#51]
I'm using pop-tools version 2020.4.30 and when using get_grid on cheyenne, pooch is trying to download CESM grid files that are already local to cheyenne. It uses `CESMDATAROOT` as a place to write these files, which causes the error because that's not a location that I have permissions to write to.  Pretty sure other CESM tools use `CESMDATAROOT`, which is set by default for me to `/glade/p/cesmdata/cseg`.  

```
import pop_tools
pop_tools.get_grid('POP_gx1v7')['REGION_MASK']

Traceback (most recent call last):
  File "/glade/u/home/emaroon/miniconda3/lib/python3.7/site-packages/pooch/utils.py", line 279, in make_local_storage
    with tempfile.NamedTemporaryFile(dir=path):
  File "/glade/u/home/emaroon/miniconda3/lib/python3.7/tempfile.py", line 547, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/glade/u/home/emaroon/miniconda3/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/glade/p/cesmdata/cseg/tmpodosnjdc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/glade/u/home/emaroon/miniconda3/lib/python3.7/site-packages/pop_tools/grid.py", line 76, in get_grid
    horiz_grid_fname = INPUTDATA.fetch(grid_attrs['horiz_grid_fname'], downloader=downloader)
  File "/glade/u/home/emaroon/miniconda3/lib/python3.7/site-packages/pooch/core.py", line 564, in fetch
    make_local_storage(str(self.abspath))
  File "/glade/u/home/emaroon/miniconda3/lib/python3.7/site-packages/pooch/utils.py", line 293, in make_local_storage
    raise PermissionError(" ".join(message)) from error
PermissionError: [Errno 13] Permission denied: '/glade/p/cesmdata/cseg/tmpodosnjdc' | Pooch could not write to data cache folder '/glade/p/cesmdata/cseg'. Will not be able to download data files.
```

Setting `CESMDATAROOT` to my scratch space temporarily solves the issue.

**Comment by andersy005** [comment]
This sounds like a bug. 

Recently, there were some new changes in` pooch` (the package used by pop-tools to manage assets download), and I believe these changes may have caused this issue.  I will look into this.

**Comment by matt-long** [comment]
This issue is cropping up for me now too. A work-around remains to be setting `CESMDATAROOT` to a directory where I have write privileges.

**Comment by andersy005** [comment]
@matt-long, #52 is meant to address this issue. Does it work on your end?

**Comment by matt-long** [comment]
I won't have a chance to test in the near term.

**Comment by andersy005** [comment]
No worries... I will coordinate with @mnlevy1981 to confirm that #52 is working properly and then I will merge it.
